using Dates
now()
Date(now())
year(now())
day(now())
dayofweek(now())
birthdate=Date(2001,5,31)
dayname(now())
daysinmonth(now())
date_format=DateFormat("dd-mm-yyyy")
Dates.format(now(), date_format)
hour(now())
second(now())
minute(now())